### ISSUE TITLE
papers

### ISSUE THREAD

**Issue by codeman6688** [sk-surya/solver-train-scheduler#1]
I am very interested in this code, but I don't understand some of the code. Can you provide relevant papers? Thank you very much.

**Comment by sk-surya** [comment]
A very high level overview of what the code does:
1. We define a simulation environment of the rail network parameterized by start time, headways and dwell times. By running a simulation with an input parameter set, one can obtain a feasible solution.
2. A metaheuristic framework tries different parameter sets to optimize the total waiting time objective (based on the demand data).
Note - The simulation doesn't handle conflicts between trains launched from different depots. Can be done if needed. For my use case, it wasn't needed, all I needed was to get an approximation of headways, dwell times and start times so that passenger congestion/wait time is minimized.

The idea itself is a very general/usual way of optimizing a simulation problem (an optimization framework that runs a parameterized construction heuristic). 
See [https://en.wikipedia.org/wiki/Simulation-based_optimization].

A relevant and a good paper to understand train timetabling problem under demand data that also uses a metaheuristic algorithm: "Single-line rail rapid transit timetabling under dynamic
passenger demand" by Barrena et al.
